name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/netrc@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Install gems
        run: bundle install

      - name: Install SwiftLint
        run: brew install swiftlint
        
      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-/...

      - name: Run Tests
        run: bundle exec fastlane scan
        
      - name: ChatGPT Reviewer
        uses: feiskyer/ChatGPT-Reviewer@v0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          

