name: Pull Request
permissions:
  contents: read
  pull-requests: write
  
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/netrc@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
   
      - name: Create Keychains
        run: |
          security create-keychain -p "$CERTIFICATE_PASSWORD" ~/Library/Keychains/login.keychain-db
          security default-keychain -s ~/Library/Keychains/login.keychain-db

      - name: Debug Certificate and Keychain
        run: |
          echo "Certificate and Keychain Debug Info:"
          echo "$CERTIFICATE" | base64 --decode | head
          security list-keychains

      - name: Decrypt and install certificate
        env:
          CERTIFICATE: ${{ secrets.DISTRIBUTION_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE" | base64 --decode > certificate.p12
          security unlock-keychain -p "$CERTIFICATE_PASSWORD" ~/Library/Keychains/login.keychain-db
          security import certificate.p12 -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "$CERTIFICATE_PASSWORD" ~/Library/Keychains/login.keychain-db

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Install gems
        run: bundle install

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-/...

      - name: Run Tests
        run: bundle exec fastlane scan
