name: Pull Request
permissions:
  contents: read
  pull-requests: write
  
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/netrc@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Fastlane
        run: gem install fastlane

      - name: Set up certificates and profiles
        env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          bundle exec fastlane match development --type appstore


      - name: Unlock keychain
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          security unlock-keychain -p "$CERTIFICATE_PASSWORD" ~/Library/Keychains/login.keychain-db

      - name: Set up certificates and profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match development --type appstore

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Install gems
        run: bundle install

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-/...

      - name: Run Tests
        run: bundle exec fastlane scan
